### ISSUE TITLE
go get error

### ISSUE THREAD

**Issue by userbl** [go-goracle/goracle#142]
I'm using GoLang IDE.
When I import "gopkg.in/goracle.v2"
I got an error.

package main

import (
	"database/sql"
	"fmt"
	_ "gopkg.in/goracle.v2"
	"log"
	"os"
	"time"
)

GOROOT=E:\golang\go #gosetup
GOPATH=E:\golang\project #gosetup
E:\golang\go\bin\go.exe get -t -v gopkg.in/goracle.v2/... #gosetup
Fetching https://gopkg.in/goracle.v2?go-get=1
Parsing meta tags from https://gopkg.in/goracle.v2?go-get=1 (status code 200)
get "gopkg.in/goracle.v2": found meta tag get.metaImport{Prefix:"gopkg.in/goracle.v2", VCS:"git", RepoRoot:"https://gopkg.in/goracle.v2"} at https://gopkg.in/goracle.v2?go-get=1
gopkg.in/goracle.v2 (download)
gopkg.in/goracle.v2

In file included from E:\golang\project\src\gopkg.in\goracle.v2\odpi\embed/dpi.c:37:0,
                 from E:\golang\project\src\gopkg.in\goracle.v2\drv.go:51:
E:\golang\project\src\gopkg.in\goracle.v2\odpi\embed/../src/dpiOci.c: In function 'dpiOci__getLoadErrorOnWindows':
E:\golang\project\src\gopkg.in\goracle.v2\odpi\embed/../src/dpiOci.c:1562:38: error: 'ERROR_MUI_FILE_NOT_FOUND' undeclared (first use in this function)
     if (!status && GetLastError() == ERROR_MUI_FILE_NOT_FOUND)
                                      ^
E:\golang\project\src\gopkg.in\goracle.v2\odpi\embed/../src/dpiOci.c:1562:38: note: each undeclared identifier is reported only once for each function it appears in

What should I  do to fix this? Thanks !

**Comment by tgulacsi** [comment]
What is your Go's version? What is your C compiler?


It works with tdm-gcc 5.1 and go v1.12.1.




On Thu, Mar 21, 2019 at 9:33 AM +0100, "userbl" <notifications@github.com> wrote:












I'm using GoLang IDE.

When I import "gopkg.in/goracle.v2"

I got an error.


package main


import (

"database/sql"

"fmt"

_ "gopkg.in/goracle.v2"

"log"

"os"

"time"

)


GOROOT=E:\golang\go #gosetup

GOPATH=E:\golang\project #gosetup

E:\golang\go\bin\go.exe get -t -v gopkg.in/goracle.v2/... #gosetup

Fetching https://gopkg.in/goracle.v2?go-get=1

Parsing meta tags from https://gopkg.in/goracle.v2?go-get=1 (status code 200)

get "gopkg.in/goracle.v2": found meta tag get.metaImport{Prefix:"gopkg.in/goracle.v2", VCS:"git", RepoRoot:"https://gopkg.in/goracle.v2"} at https://gopkg.in/goracle.v2?go-get=1

gopkg.in/goracle.v2 (download)

gopkg.in/goracle.v2


In file included from E:\golang\project\src\gopkg.in\goracle.v2\odpi\embed/dpi.c:37:0,

from E:\golang\project\src\gopkg.in\goracle.v2\drv.go:51:

E:\golang\project\src\gopkg.in\goracle.v2\odpi\embed/../src/dpiOci.c: In function 'dpiOci__getLoadErrorOnWindows':

E:\golang\project\src\gopkg.in\goracle.v2\odpi\embed/../src/dpiOci.c:1562:38: error: 'ERROR_MUI_FILE_NOT_FOUND' undeclared (first use in this function)

if (!status && GetLastError() == ERROR_MUI_FILE_NOT_FOUND)

^

E:\golang\project\src\gopkg.in\goracle.v2\odpi\embed/../src/dpiOci.c:1562:38: note: each undeclared identifier is reported only once for each function it appears in


What should I  do to fix this? Thanks !

**Comment by userbl** [comment]
go version:   go1.12.1.windows-386.zip
gcc version 4.9.3 (GCC)

now, I update the compiler to gcc version 8.1.0 (x86_64-posix-seh-rev0, Built by MinGW-W64 project)
and go version to go1.12.1.windows-amd64

I got new error

 username="abc" SID="eger@192.168.2.10:1521/testdb" minSessions=1 maxSessions=1000 poolIncrement=1 extAuth=0 : ORA-12154: TNS:could not resolve the connect identifier specified
panic: username="abc" SID="eger@192.168.2.10:1521/testdb" minSessions=1 maxSessions=1000 poolIncrement=1 extAuth=0 : ORA-12154: TNS:could not resolve the connect identifier specified
	panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x0 pc=0x4d16ad]


oracleDB, err := sql.Open("goracle", "abc/wef@eger@192.168.2.10:1521/testdb")

may be problem is  the password contains the  letter "@" .

**Comment by tgulacsi** [comment]
Great news!
This means the library compiles, and is usable!

For strange passwords/usernames, build the session string with goracle.ConnectionParam{...}.StringWithPassword().
